config/routes.rb
Rails.application.routes.draw do
  root "locations#index"
  resources :locations do
    collection do
      post :index
      post :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
# frozen_string_literal: true
class Location < ApplicationRecord
  validates :url, uniqueness: true
  validates :ip_address, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include Pagy::Backend

  before_action :check_input, only: [:search]

  def index
    @pagy, @locations = pagy(Location.order(created_at: :desc), items: 10)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def search
    existing_location ? respond_with_existing_location : respond_with_new_location
  end

  private

  def respond_with_existing_location
    @location = existing_location
    @message = 'Location is taken from saved'

    respond
  end

  def respond_with_new_location
    creator = LocationCreator.new(@search_params)
    creator.call
    @location = creator.location
    @message = creator.message
    @created = creator.created

    respond
  end

  def respond
    respond_to do |format|
      format.turbo_stream
    end
  end

  def existing_location
    @existing_location = LocationFinder.new(search_params).call
  end

  def search_params
    permitted_params = params.permit(:source, :type).to_unsafe_hash
    @search_params ||= SearchParamsBlueprint.render_as_hash(permitted_params)
  end

  def source
    @source ||= search_params[:source]
  end

  def type
    @type ||= search_params[:type]
  end

  def check_input
    contract = LocationsCreateContract.new.call(search_params)
    if contract.failure?
      @message = contract.errors.to_h.values.join(',')

      respond
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geolocator2</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "https://unpkg.com/leaflet@1.7.1/dist/leaflet.css", integrity: "sha256-BPfK9M5v34c2XP6p0cxVz1mUQLst0gTLk0mlc7kuodA=", crossorigin: "" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<main>
  <%= yield %>
</main>
<%= javascript_include_tag "https://unpkg.com/leaflet@1.7.1/dist/leaflet.js", integrity: "sha256-yDc0eil8GjWFKqN1OSzHSVCiuGghTosZCcRje4tj7iQ=", crossorigin: "", defer: true %>
</body>
</html>

app/views/locations/_load_more_button.html.erb
<% if @pagy.next.present? %>
  <%= button_to "Load more", locations_path, params: { page: @pagy.next }, method: :get, "data-turbo-stream": true %>
<% end %>

app/views/locations/_location_content.html.erb
<div class="cell"><%= location.url %></div>
<div class="cell"><%= location.ip_address %></div>
<div class="cell"><%= location.latitude %></div>
<div class="cell"><%= location.longitude %></div>

app/views/locations/_location_table.html.erb
<table>
  <thead>
  <tr>
    <th>URL</th>
    <th>IP</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= location.url %></td>
    <td><%= location.ip_address %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
  </tr>
  </tbody>
</table>

app/views/locations/_locations_list.html.erb
<div class="locations-grid">
  <div class="row header">
    <div class="cell">URL</div>
    <div class="cell">IP</div>
    <div class="cell">Latitude</div>
    <div class="cell">Longitude</div>
  </div>
  <turbo-frame id="locations_content_frame">
    <% @locations.each do |location| %>
      <div class="row">
        <%= render partial: 'location_content', locals: { location: location } %>
      </div>
    <% end %>
  </turbo-frame>
</div>

app/views/locations/_search_form.html.erb
<%= form_with url: search_locations_path, method: :post, data: { turbo_frame: 'search_result' } do |form| %>
  <div>
    <label>
      <%= form.radio_button :type, 'url', checked: true %>
      URL
    </label>
    <label>
      <%= form.radio_button :type, 'ip_address' %>
      IP
    </label>
    <%= form.text_field :source, placeholder: 'type url here', required: true %>
    <%= form.submit 'Find location!' %>
  </div>
<% end %>

app/views/locations/_search_result.html.erb
<turbo-frame id="search_result">
  <% if @message %>
    <p><%= @message %></p>
  <% end %>

  <% if @location.present? %>
    <%= render partial: 'location_table', locals: { location: @location } %>
    <div id="map" data-controller="map"
         data-map-target="map"
         data-map-latitude="<%= @location.latitude %>"
         data-map-longitude="<%= @location.longitude %>"
         style="height: 500px;"></div>
  <% end %>
</turbo-frame>

app/views/locations/index.html.erb
<div class="container">
  <h1>Geolocator</h1>

  <div>
    <%= render 'search_form' %>
  </div>

  <h2>Location:</h2>
  <turbo-frame id="search_result">
  </turbo-frame>

  <h2>Saved locations:</h2>
  <div>
    <%= render 'locations_list', locations: @locations %>

    <turbo-frame id="more">
      <%= render 'load_more_button' %>
    </turbo-frame>
  </div>
</div>

app/views/locations/index.turbo_stream.erb
<%= turbo_stream.append 'locations_content_frame' do %>
  <% @locations.each do |location| %>
    <div class="row">
      <%= render partial: 'location_content', locals: { location: location } %>
    </div>
  <% end %>
<% end %>

<%= turbo_stream.update "more" do %>
  <%= render "load_more_button" %>
<% end %>

app/views/locations/search.turbo_stream.erb
<%= turbo_stream.replace "search_result" do %>
  <%= render 'search_result', locals: { locations: @location, message: @message } %>
<% end %>

<% if @created %>
  <%= turbo_stream.prepend 'locations_content_frame' do %>
    <div class="row">
      <%= render partial: 'location_content', locals: { location: @location } %>
    </div>
  <% end %>
<% end %>